# Site settings
title: "Lembaga Sertifikasi Profesi"
description: "Universitas Singaperbangsa Karawang"
url: "lsp.unsika.ac.id"
author:
  name: "LSP Unsika"
  email: ""
  url: ""

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project-page"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false


# collections:
  # projects:
  #   output: true
